spring.application.name=FT_TRANSCENDENCE


spring.datasource.url=jdbc:postgresql://localhost:5432/lopo
spring.datasource.username=postgres
spring.datasource.password=roote


spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.web.error.include-exception=false
spring.web.error.include-stacktrace=never


spring.jpa.hibernate.ddl-auto=create

vigil.jwt-secret=${JWT_SECRET:2=34H6789E*/Bghjklwrehqef54564564q54qefqef4qe54fgeqgqe4fveqwv354315wrnfse*/-/q231*}

vigil.access-token-expiration=900000
vigil.refresh-token-expiration=2592000000



spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.property-naming-strategy=SNAKE_CASE