spring.application.name=FT_TRANSCENDENCE
spring.datasource.url=jdbc:postgresql://localhost:5432/lopo
spring.datasource.username=postgres
spring.datasource.password=roote
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.web.error.include-exception=false
spring.web.error.include-stacktrace=never
spring.jpa.hibernate.ddl-auto=create
spring.jackson.deserialization.fail-on-unknown-properties=true
jwt.secret=${JWT_SECRET:2=34H6789E*/Bghjklwrehqef54564564q54qefqef4qe54fgeqgqe4fveqwv354315wrnfse*/-/q231*}
jwt.expiration=900000
jwt.refrech_expiration=2592000000